### ISSUE TITLE
Eksik bilgi!

### ISSUE THREAD

**Issue by HilOzd** [serhat-akbas/dev-env-setup#1]
Merhaba,
Visual Studio Community kütüphaneleri ile ilgili detaylı bilgi verilmemiş. Ayrıca Git for Windows linki eksik. Bilgilerin kullanıcıların faydası için eklenilmesinin faydalı olacağını düşünüyorum.

**Comment by serhat-akbas** [comment]
Öneriniz için teşekkürler. README güncellendi (#2).
